# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqoHo2Cw-1l73oNuhLKfwPFzCIMv90WJ
"""

!pip install pykrx yfinance pandas requests --quiet
print("✅ 패키지 설치 완료!")

import os

os.environ['KRX_ID'] = 'sehoon3300'      # KRX 회원 ID
os.environ['KRX_PW'] = 'Helloguy0931!'  # KRX 비밀번호

print("✅ KRX 로그인 정보 설정 완료!")

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pykrx import stock
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# ================== 설정 ==================
GMAIL_ID = 'biryong13@gmail.com'
GMAIL_APP_PASSWORD = 'kwkn aywl xyeh slyt'

RECEIVER_EMAIL = 'biryong13@gmail.com'

portfolio = {
    '360750': 'TIGER 미국S&P500',
    '448300': 'TIGER 미국나스닥100(H)',
    '402970': 'ACE 미국배당다우존스',
    '069500': 'KODEX 200',
    '411060': 'ACE KRX금현물',
    '305080': 'TIGER 미국채10년선물'
}
# =========================================

def send_gmail(subject, body):
    msg = MIMEMultipart()
    msg['From'] = GMAIL_ID
    msg['To'] = RECEIVER_EMAIL
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'html'))
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(GMAIL_ID, GMAIL_APP_PASSWORD)
        server.send_message(msg)
        server.quit()
        print("✅ Gmail 전송 완료!")
    except Exception as e:
        print("❌ Gmail 전송 실패:", e)

def get_morning_report():
    today = datetime.today().strftime('%Y-%m-%d')
    yesterday = (datetime.today() - timedelta(days=1)).strftime('%Y%m%d')

    html = f"""
    <h2>📅 {today} 아침 포트폴리오 브리핑</h2>
    <p><b>전일({yesterday}) 기준</b></p>
    <hr>
    <h3>📊 포트폴리오 현황</h3>
    <table border="1" cellpadding="8" style="border-collapse: collapse;">
        <tr><th>종목</th><th>종가</th><th>등락률</th></tr>
    """

    for ticker, name in portfolio.items():
        try:
            df = stock.get_market_ohlcv(yesterday, yesterday, ticker)
            if not df.empty:
                row = df.iloc[-1]
                close = int(row['종가'])
                change = row['등락률']
                html += f"<tr><td>{name}</td><td>{close:,}</td><td>{change:+.2f}%</td></tr>"
        except:
            html += f"<tr><td>{name}</td><td>오류</td><td>-</td></tr>"

    html += "</table>"

    html += "<p><small>⚠️ 참고용 자료입니다. 실제 투자 판단은 본인 책임입니다.</small></p>"

    send_gmail(f"[{today}] 아침 포트폴리오 브리핑", html)

# 실행
get_morning_report()